SELECT
    element_id
    , event_id
    , fixture_id
    , opponent_team_id
    , was_home
    , team_h_score
    , team_a_score
    , total_points
    , bps
    , bonus
    , starts
    , minutes_played
    , goals_scored
    , expected_goals
    , assists
    , expected_assists
    , expected_goal_involvements
    , goals_conceded
    , expected_goals_conceded
    , clean_sheets
    , saves
    , own_goals
    , penalties_saved
    , penalties_missed
    , tackles
    , recoveries
    , clearances_blocks_interceptions
    , defensive_contribution
    , yellow_cards
    , red_cards
    , ict_index
    , threat
    , creativity
    , influence
    , transfers_in
    , transfers_out
    , transfers_balance
    , selected
    , value
FROM {{ref("cleansed_element_summaries_round")}}